title: My Fashion Blog
author: Jessica Salewski
email: jsalewski@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is my new fashion blog.  The goal of my site is to help you create your own fashion capsules all based on the clothes you already have in your closet. With miminum shopping needed.  You may need to buy some basics, but this will help you figure out what you don't need and pare down your closet to perfection.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
